apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy-box
  name: busy-box
spec:
  containers:
  - args:
    - sh
    - -c
    - ls; echo 'hello world'; echo 'how are you'
    image: busybox
    name: busy-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
