apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: prod
    app: ui
  name: busy-box
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: busy-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    hardware: ssd
status: {}
