apiVersion: v1
kind: Pod
metadata:
  name: pod-secret1
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-secret1
    envFrom:
    - secretRef:
        name: app-secret
  restartPolicy: Never
