apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-config1
  name: pod-config1
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: pod-config1
    envFrom:
    - configMapRef:
        name: app-config
  restartPolicy: Never
