apiVersion: v1
kind: Pod
metadata:
  name: sec-ctx-pod2
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: sec-ctx-cont2
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
