apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy-box
  name: busy-box
spec:
  containers:
  - command:
    - sh
    - -c
    - pwd; echo 'hello world'; sleep 10;
    image: busybox
    name: busy-box
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
