apiVersion: v1
kind: Pod
metadata:
        name: ubuntu-sleeper
spec:
        containers:
        - name: ubuntu-sleeper
          image: ubuntu
          command: [/bin/sh]
          args: ["-c", "echo 'hello world'; pwd; ls;exit"]
